name: 'Generate SOUP register'
author: 'Rik van Duijn'
description: 'Automatically generate a SOUP register for JS based projects'
branding:
  icon: 'clipboard'
  color: 'purple'
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    default: ${{ github.token }}
