name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false

      - name: Build distribution
        run: yarn build

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            dist

      - name: Fail if dist has uncommitted changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('dist folder has uncommitted changes! Run `yarn build` and commit the resulting changes.')
