name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          continue_on_error: false
